// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIvoEAaPyKHYH6YtW8lSmRtQGW8zysRc',
    appId: '1:669260082445:web:ae2b5f662783b356b45444',
    messagingSenderId: '669260082445',
    projectId: 'barber-10ed3',
    authDomain: 'barber-10ed3.firebaseapp.com',
    storageBucket: 'barber-10ed3.firebasestorage.app',
    measurementId: 'G-R8VBNL53HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzbbU7wXbrHW33mI39KIUTfAMG2t13Vk',
    appId: '1:669260082445:android:f571a0f274e97200b45444',
    messagingSenderId: '669260082445',
    projectId: 'barber-10ed3',
    storageBucket: 'barber-10ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe8p-_q_vtC15i3epPoBTWDojuvPDBHLc',
    appId: '1:669260082445:ios:6f46a4ef2178d6f3b45444',
    messagingSenderId: '669260082445',
    projectId: 'barber-10ed3',
    storageBucket: 'barber-10ed3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe8p-_q_vtC15i3epPoBTWDojuvPDBHLc',
    appId: '1:669260082445:ios:6f46a4ef2178d6f3b45444',
    messagingSenderId: '669260082445',
    projectId: 'barber-10ed3',
    storageBucket: 'barber-10ed3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYIvoEAaPyKHYH6YtW8lSmRtQGW8zysRc',
    appId: '1:669260082445:web:7432cdfa31a03165b45444',
    messagingSenderId: '669260082445',
    projectId: 'barber-10ed3',
    authDomain: 'barber-10ed3.firebaseapp.com',
    storageBucket: 'barber-10ed3.firebasestorage.app',
    measurementId: 'G-WRZ8MKK8BJ',
  );
}
